version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_LOCAL_URL=mongodb://mongo:27017/wander # Update this URL if necessary
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017" # Change the host port to a different port, for example, 27018
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
