version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_LOCAL_URL=mongodb://mongo:27017/wander
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
